### ISSUE TITLE
Update Vanilla OS file when it reaches 2.0

### ISSUE THREAD

**Issue by SteveLauC** [which-distro/os-release#1]
When Vanilla OS reaches 2.0, it will be based on Debian instead of Ubuntu, at that time, it will have its own `ID` field `vanilla` in the `os-release` file.

For more info, see their [roadmap](https://vanillaos.org/roadmap)

**Comment by curbengh** [comment]
I think this can be closed, v2 stable was released without a unique `ID`.

**Comment by SteveLauC** [comment]
Right, let's close it😄
