### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by grooverdan** [which-distro/os-release#7]
I don't have a sample currently, however I note that /etc/os-release is FreeBSD supported.

https://man.freebsd.org/cgi/man.cgi?query=os-release&sektion=&manpath=freebsd-release-ports

Thanks for the service. this helped me a lot in implementing https://github.com/MariaDB/server/pull/2818

**Comment by SteveLauC** [comment]
I am really glad this helped you, let's me set up a FreeBSD VM and add it
